config/routes.rb
AdiskNew::Application.routes.draw do

  devise_for :users

  root :to => "dashboard#index"

  match 'test_index' => 'dashboard#test_index'
  match 'test_form' => 'dashboard#test_form'

  resources :users
  resources :chainlets
  resources :responsibility_centres

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
  				# :registerable,
        	# :recoverable,
        	# :rememberable,
        	:trackable,
        	:validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, 
                  :password, 
                  :password_confirmation,
                  :login, 
                  :remember_me, 
                  :first_name, 
                  :patronomic, 
                  :last_name,
                  :position,
                  :extension_number,
                  :cell_phone,
                  :icq,
                  :skype,
                  :city,
                  :comment,
                  :user_roles_attributes

  # Simple roles plugin - user have ine or many roles within has_many_througth association
  simple_roles


  # References

  # This is self reference block - user can HAVE another users as his posible subtituents
  # for user who IS substituent on the other hand - user for whom hi substitute appears as appointive
  # so it works with simple reflection - but not goes both ways (user1 is sub for user2, but u2 may not be a sub for u1
  # while he WILL be apoointive for u1)

  # Simple (well, not simple actualy, takes time to figure it out) self reference - user can have many over user as substituents
  # self join goes through model Deputy, sine i need some logic and attr be place in this middleware
  has_many :deputies, :foreign_key => "appointive_id" #, :include => :sub
  has_many :subs, :class_name => "User", :through => :deputies, :foreign_key => "appointive_id"

  # Tricky part: since i can not find a way to use a named scope for a assocition :trought i create a new one. It basicly the 
  # same deputy association, but with conditions.
  # Also i change it from has_many to has_one - while user can have multiply posible subs, he can only have 1 active substituent
  has_one :active_deputy, :class_name => "Deputy", :foreign_key => "appointive_id", :conditions => {:is_active => true}
  has_one :active_sub, :class_name => "User", :through => :active_deputy, :foreign_key => "appointive_id", :source => :sub

  # All the same but in the opposite way. Thats why i call it reverse_ .
  has_many :reverse_deputies, :class_name => "Deputy", :foreign_key => "sub_id"
  has_many :appointives, :class_name => "User", :through => :reverse_deputies, :foreign_key => "sub_id"

  # has_many back again. Why? User can accept substituenship from many user simultaneously.
  has_many :active_reverse_deputies, :class_name => "Deputy", :foreign_key => "sub_id", :conditions => {:is_active => true}
  has_many :active_appointives, :class_name => "User", :through => :active_reverse_deputies, :foreign_key => "sub_id", :source => :appointive


  # Need to accept atributes througth nested form
  accepts_nested_attributes_for :user_roles, :allow_destroy => true, :reject_if => lambda {|r| !r[:active]}


  # Validations
  validates :email, :presence => true
  validates :password, :presence => true, :confirmation => true, :length => {:minimum => 7}


  # Instance methods
  def full_name
    last_name + " " + first_name + " " + patronomic
  end

  def initials
    last_name + " " + first_name.first_letter + ". " + patronomic + "."
  end

  def activate_sub(user)
    # rise an exception if given user is not User class instance
    dep = deputies.where(:sub_id => user.id).first
    dep.is_active = true
    dep.save!
  end

  def user_and_active_appointives
    UsersArray.new(self)
  end

  private
  def asign_roles
    unless :roles.nil?
      roles = :roles
      add_role :user
    end
  end


  # Utility class for user acts as an array of users.
  class UsersArray < Array

    attr_reader :base
    include UsersArrayExtension

    def initialize *args
      @user = args.delete(args.first)
      super
      extend_with_active_appointives
    end

    private
    def extend_with_active_appointives
      self << @user
      self << @user.active_appointives
      self.flatten!
    end
  end
end

class Deputy < ActiveRecord::Base
  # References
  belongs_to :appointive, :class_name => "User"
  belongs_to :sub, :class_name => "User"

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	# load_and_authorize_resource
  # uncomment lately
  
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    @roles = Role.all
    @roles.each do |r|
      @user.user_roles.build :role_id => r.id
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/views/users/_form.haml
= form_for user, :validate => true, :builder => AdiskFormBuilder, :html => {:class => "document-form form-horizontal"} do |f|
  - f.display_label = false

  %div.row
    = f.column do
      = f.fieldset "Основная информация" do
        = f.prepended_for :last_name, :text, :placeholder => "Фамилия", :icon => "user"
        = f.prepended_for :first_name, :text, :placeholder => "Имя", :icon => "user"
        = f.prepended_for :patronomic, :text, :placeholder => "Отчество", :icon => "user"

      = f.fieldset "Логин" do
        = f.prepended_for :email, :text, :placeholder => "email", :icon => "envelope", :hint => "hello"
        = f.prepended_for :password, :password, :placeholder => "Пароль", :icon => "key"
        = f.prepended_for :password_confirmation, :password, :placeholder => "Подтверждение пароля", :icon => "key"
        
      = f.fieldset "Должность" do
        = f.prepended_for :position, :text, :placeholder => "Должнолсть", :icon => "home"

      = f.fieldset "Информация" do
        = f.prepended_for :extension_number, :text, :placeholder => "Внутренний номер", :icon => "volume-down"
        = f.prepended_for :cell_phone, :text, :placeholder => "Мобильный телефон", :icon => "volume-up"
        = f.prepended_for :icq, :text, :placeholder => "ICQ", :icon => "align-left"
        = f.prepended_for :skype, :text, :placeholder => "Skype", :icon => "comments"
        = f.prepended_for :city, :text, :placeholder => "Город", :icon => "home"


    = f.column do
      = f.fieldset "Роли" do
        = f.fields_for :user_roles do |r|
          = r.hidden_field :role_id
          %label.checkbox
            = r.check_box :active
            = r.object.role.name.capitalize

      = f.fieldset "Комментарий" do
        = f.prepended_for :comment, :textarea, :placeholder => "Комментарий", :icon => "pencil", :rows => 5
  %div.row
    = f.form_actions

app/views/users/edit.haml
%div{:class => "content-header clearfix"}
  %div{:class => "row"}
    %div{:class => "span10"}
      %h3 Новый пользователь

%div.row
  %div.span8
    / = debug @user.user_roles
    = render :partial => 'form', :locals => {:user => @user}

app/views/users/index-grid.haml
%div{:class => "content-header clearfix"}
  %div{:class => "row"}
    %div{:class => "span10"}
      %h3 Пользователи
      %div{:class => "span2 pull-right"}
        %a.act.success{:href => "#{new_user_path}"}
          Создать
          %i.icon-star-empty.icon-large.pull-right


  %div{:class => "row"}
    %div{:class => "span10"}
      %ul{:class => "breadcrumb"}
        %li{:class => "active"}
          В работе
          %span.divider /
        %li
          %a{:href => "#"} На подписи
          %span.divider /
        %li
          %a{:href => "#"} Принятые
          %span.divider /
        %li
          %a{:href => "#"} Отклоненные

- @users.each do |user|
  %div.row.user
    %div.span
      %a(href="#{user_path(user)}")
        %img(src="http://placehold.it/120x120" alt="")
    %div.span3
      %p
        %strong Логин: 
        %span dubinin
      %p
        %strong email: 
        %span= user.email
      %p
        %strong Фамилия: 
        %span Дубинин
      %p
        %strong Имя
        %span Роман
      %p
        %strong Отчество 
        %span Евгеньевич
    %div.span3
      %p
        %strong Роли:
        %span Пользователь, Администратор
      %p
        %strong Заместители:
        %span Шуров Михаил Вадимович, Виквик
    %div.span2.pull-right
      %a.act{:href => "#{user_path(user)}"}
        Подробнее
        %i.icon-arrow-right.icon-large.pull-right
      %a.act.danger{:href => "#{user_path(user)}"}
        Заблокировать
        %i.icon-lock.icon-large.pull-right

app/views/users/index.haml
%div{:class => "content-header clearfix"}
  %div{:class => "row"}
    %div{:class => "span10"}
      %h3 Пользователи
      %div{:class => "span2 pull-right"}
        %a.act.success{:href => "#{new_user_path}"}
          Создать
          %i.icon-star-empty.icon-large.pull-right


  %div{:class => "row"}
    %div{:class => "span10"}
      %ul{:class => "breadcrumb"}
        %li{:class => "active"}
          В работе
          %span.divider /
        %li
          %a{:href => "#"} На подписи
          %span.divider /
        %li
          %a{:href => "#"} Принятые
          %span.divider /
        %li
          %a{:href => "#"} Отклоненные

= index_table_for @users do |table|
  - table.add_column :name => :id, :header => "#", :method => :id
  - table.add_column :name => :email, :header => "email", :method => :email

  - table.add_control :type => :info, :icon => "arrow-right", :action => :show, :path => lambda {|obj| user_path(obj)}
  - table.add_control :type => :info, :icon => "edit", :action => :edit, :path => lambda {|obj| edit_user_path(obj)}
  - table.add_control :type => :danger, :icon => "lock", :action => :delete, :path => lambda {|obj| user_path(obj)}

app/views/users/new.haml
%div{:class => "content-header clearfix"}
  %div{:class => "row"}
    %div{:class => "span10"}
      %h3 Новый пользователь

%div.row
  %div.span8
    = render :partial => 'form', :locals => {:user => @user}