config/routes.rb
AdiskNew::Application.routes.draw do

  devise_for :users

  root :to => "dashboard#index"

  match 'test_index' => 'dashboard#test_index'
  match 'test_form' => 'dashboard#test_form'

  resources :users
  resources :chainlets
  resources :responsibility_centres

end

app/models/chainlet.rb
class Chainlet < ActiveRecord::Base
	has_many :chainlet_links, :dependent => :destroy
	accepts_nested_attributes_for :chainlet_links

  def get_id
    id.to_s
  end

  def get_comment
    if respond_to? :description
      unless comment.blank?
        comment
      else
        "---"
      end
    else
      raise NoMethodError.new "You model have no comment at all to get."
    end
  end

end

# Since one link does not have specific controller and views - jst keep it here
class ChainletLink < ActiveRecord::Base
	belongs_to :chainlet
	validates :ordinal_number, :presence => true
end

app/controllers/chainlets_controller.rb
class ChainletsController < ApplicationController
	# load_and_authorize_resource
  # uncomment lately
  
  # GET /chainlets
  # GET /chainlets.json
  def index
    @chainlets = Chainlet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @chainlets }
    end
  end

  # GET /chainlets/1
  # GET /chainlets/1.json
  def show
    @chainlet = Chainlet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chainlet }
    end
  end

  # GET /chainlets/new
  # GET /chainlets/new.json
  def new
    @chainlet = Chainlet.new
    3.times do |t|
      @chainlet.chainlet_links.build
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chainlet }
    end
  end

  # GET /chainlets/1/edit
  def edit
    @chainlet = Chainlet.find(params[:id])
  end

  # POST /chainlets
  # POST /chainlets.json
  def create
    @chainlet = Chainlet.new(params[:chainlet])

    respond_to do |format|
      if @chainlet.save
        format.html { redirect_to @chainlet, notice: 'Chainlet was successfully created.' }
        format.json { render json: @chainlet, status: :created, location: @chainlet }
      else
        format.html { render action: "new" }
        format.json { render json: @chainlet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /chainlets/1
  # PUT /chainlets/1.json
  def update
    @chainlet = Chainlet.find(params[:id])

    respond_to do |format|
      if @chainlet.update_attributes(params[:chainlet])
        format.html { redirect_to @chainlet, notice: 'Chainlet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @chainlet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chainlets/1
  # DELETE /chainlets/1.json
  def destroy
    @chainlet = Chainlet.find(params[:id])
    @chainlet.destroy

    respond_to do |format|
      format.html { redirect_to chainlets_url }
      format.json { head :no_content }
    end
  end
end

app/views/chainlets/index.haml
= page_header do |header|

  - header.headline = "Бизнес-процессы"

  - header.add_action "Создать", new_chainlet_path,:type => "success", :icon => "star-empty"

  - header.add_crumb "Все", "all", :icon => "user"
  - header.add_crumb "Активные", "active", :icon => "user"
  - header.add_crumb "Заблокированные", "block", :icon => "user"


= index_table_for @chainlets do |table| 
  - table.add_column :name => :id, :header => "#", :method => :get_id
  - table.add_column :name => :title, :header => "Название", :method => :title
  - table.add_column :name => :description, :header => "Описание", :method => :description
  - table.add_column :name => :comment, :header => "Комментарий", :method => :get_comment


  - table.add_control :type => :info, :icon => "arrow-right", :action => :show, :path => lambda {|obj| chainlet_path(obj)}
  - table.add_control :type => :info, :icon => "edit", :action => :edit, :path => lambda {|obj| edit_chainlet_path(obj)}
  - table.add_control :type => :danger, :icon => "trash", :action => :delete, :path => lambda {|obj| chainlet_path(obj)}

app/views/chainlets/new.haml
= page_header do |header|

  - header.headline = "Бизнес-процессы"
  - header.back_path = chainlets_path


=form_for @chainlet, :validate => true, :builder => AdiskFormBuilder, :html => {:class => "document-form form-horizontal"} do |f|
  %div.row
    =f.column do
      =f.fieldset "Процесс" do
        =f.prepended_for :title, :text, :icon => "font"
        =f.prepended_for :description, :text, :placeholder => "Описание", :icon => "tag"
    =f.column do
      =f.fieldset "Комментарий" do
        = f.prepended_for :comment, :textarea, :placeholder => "Комментарий", :icon => "edit", :rows => 4

  =f.sortable_list_for_nested :chainlet_links, :id => "chainlet-links" do |b|
    =b.sortable_list_element 8 do
    
      %label.radio.inline
        %input{:type => "radio"}
        %span пользователь
      %label.radio.inline
        %input{:type => "radio"}
        %span роль
      %label.radio.inline
        %input{:type => "radio"}
        %span цфо
      / %div.btn-group(data-toggle="buttons-radio" style="display:inline-block")
      /   %div.btn 
      /     %i.icon-user
      /     Пользователь
      /   %div.btn
      /     %i.icon-cog
      /     Роль
      /   %div.btn
      /     %i.icon-home
      /     Отдел
      %div.pull-right
        =b.prepended_for :link_value,  :text, :icon => "info-sign", :span => 3
        =b.prepended_for :timeout, :text, :icon => "time", :span => 2
  %div.row
    = f.form_actions