config/routes.rb
AdiskNew::Application.routes.draw do

  devise_for :users

  root :to => "dashboard#index"

  match 'test_index' => 'dashboard#test_index'
  match 'test_form' => 'dashboard#test_form'

  resources :users
  resources :chainlets
  resources :responsibility_centres

end

app/models/responsibility_centre.rb
class ResponsibilityCentre < ActiveRecord::Base
	# Scopes 
	default_scope includes(:head)

	# References
	has_many :users
	belongs_to :head, :class_name => "User", :foreign_key => :head_id

	# Validations
	validates :head_id, :presence => true
	validates :title, :presence => true
	validates :description, :presence => true

	# Instance Methods
	def get_comment
		if respond_to? :description
			unless comment.blank?
				comment
			else
				"---"
			end
		else
			raise NoMethodError.new "You model have no comment at all to get."
		end
	end

	def get_id
		id.to_s
	end

	def get_head
		head.email
	end
end

app/controllers/responsibility_centres_controller.rb
class ResponsibilityCentresController < ApplicationController
  # GET /responsibility_centres
  # GET /responsibility_centres.json
  def index
    @cfos = ResponsibilityCentre.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cfos }
    end
  end

  # GET /responsibility_centres/1
  # GET /responsibility_centres/1.json
  def show
    @cfo = ResponsibilityCentre.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cfo }
    end
  end

  # GET /responsibility_centres/new
  # GET /responsibility_centres/new.json
  def new
    @cfo = ResponsibilityCentre.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cfo }
    end
  end

  # GET /responsibility_centres/1/edit
  def edit
    @cfo = ResponsibilityCentre.find(params[:id])
  end

  # POST /responsibility_centres
  # POST /responsibility_centres.json
  def create
    @cfo = ResponsibilityCentre.new(params[:responsibility_centre])

    respond_to do |format|
      if @cfo.save
        format.html { redirect_to @cfo, notice: 'Responsibility centre was successfully created.' }
        format.json { render json: @cfo, status: :created, location: @cfo }
      else
        format.html { render action: "new" }
        format.json { render json: @cfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /responsibility_centres/1
  # PUT /responsibility_centres/1.json
  def update
    @cfo = ResponsibilityCentre.find(params[:id])

    respond_to do |format|
      if @cfo.update_attributes(params[:responsibility_centre])
        format.html { redirect_to @cfo, notice: 'Responsibility centre was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responsibility_centres/1
  # DELETE /responsibility_centres/1.json
  def destroy
    @cfo = ResponsibilityCentre.find(params[:id])
    @cfo.destroy

    respond_to do |format|
      format.html { redirect_to responsibility_centres_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/responsibility_centres_helper.rb
module ResponsibilityCentresHelper
end

app/views/responsibility_centres/_form.haml
%div.row
  %div.span8
    = form_for cfo, :validate => true, :builder => AdiskFormBuilder, :html => {:class => "document-form form-horizontal"} do |f|

      %div.row
        = f.column do
          = f.fieldset "Основная информация" do
            = f.prepended_for :title, :text, :placeholder => "Название", :icon => "font"
            = f.prepended_for :description, :text, :placeholder => "Описание", :icon => "bold"
          = f.fieldset "Основная информация" do
            = f.prepended_for :head_id, :select, :placeholder => "Руководитель", :icon => "user", :collection => User.all.map {|u| [u.email, u.id]}


        = f.column do
          = f.fieldset "Комментарий" do
            = f.prepended_for :comment, :textarea, :placeholder => "Комментарий", :icon => "pencil", :rows => 3
      %div.row
        = f.form_actions

app/views/responsibility_centres/edit.haml
= page_header do |header|

  - header.headline = "Центры Финансовой Ответвенности"
  - header.back_path = responsibility_centres_path
  
= render :partial => 'form', :locals => {:cfo => @cfo}

app/views/responsibility_centres/index.haml
= page_header do |header|

  - header.headline = "Центры Финансовой Ответвенности"

  - header.add_action "Создать", new_responsibility_centre_path,:type => "success", :icon => "star-empty"
  - header.add_action "Выгрузить", new_responsibility_centre_path,:type => "info", :icon => "download"


  - header.add_crumb "Все", "all", :icon => "user"
  - header.add_crumb "Активные", "active", :icon => "user"
  - header.add_crumb "Заблокированные", "block", :icon => "user"


= index_table_for @cfos do |table|
  - table.add_column :name => :id, :header => "#", :method => :get_id
  - table.add_column :name => :title, :header => "Название", :method => :title
  - table.add_column :name => :description, :header => "Описание", :method => :description
  - table.add_column :name => :head_name, :header => "Руководитель", :method => :get_head
  - table.add_column :name => :comment, :header => "Комментарий", :method => :get_comment


  - table.add_control :type => :info, :icon => "arrow-right", :action => :show, :path => lambda {|obj| responsibility_centre_path(obj)}
  - table.add_control :type => :info, :icon => "edit", :action => :edit, :path => lambda {|obj| edit_responsibility_centre_path(obj)}
  - table.add_control :type => :danger, :icon => "trash", :action => :delete, :path => lambda {|obj| responsibility_centre_path(obj)}

app/views/responsibility_centres/new.haml
= page_header do |header|

  - header.headline = "Центры Финансовой Ответвенности"
  - header.back_path = responsibility_centres_path
  
%div.row
  %div.span8
    / = debug @user.user_roles
    = render :partial => 'form', :locals => {:cfo => @cfo}

app/views/responsibility_centres/show.haml
= page_header do |header|

  - header.headline = "Центры Финансовой Ответвенности"
  - header.back_path = responsibility_centres_path
  