config/routes.rb
AdiskNew::Application.routes.draw do

  devise_for :users

  root :to => "dashboard#index"

  match 'test_index' => 'dashboard#test_index'
  match 'test_form' => 'dashboard#test_form'

  resources :users
  resources :chainlets
  resources :responsibility_centres

end

app/views/layouts/_nav.haml
%ul(class="nav nav-list" id="nav-main")
  %li
    %a(href="#{root_path}") В работе
  %li= link_to "На подпись", "#"
/%p(class="nav-header" data-toggle="collapse" data-target="#nav-documents") Документы
%ul(class="nav nav-list" id="nav-documents")
  %li(class="nav-header" data-toggle="collapse" data-target="#nav") Документы
  %li= link_to "Бюджеты", "#"
  %li= link_to "Заявки на оплату", "#"
  %li= link_to "Поступления", "#"
  %li= link_to "Служеные записки", "#"
  %li= link_to "Другие документы", "#"
%ul(class="nav nav-list" id="nav-repos")
  %li(class="nav-header") Справочники
  %li= link_to "Контрагенты", "#"
  %li= link_to "Счета", "#"
  %li= link_to "Организации", "#"
  %li= link_to "ЦФО", responsibility_centres_path
  %li= link_to "Статить доходов", "#"
  %li= link_to "Статить расходов", "#"
%ul(class="nav nav-list" id="nav-reports")
  %li(class="nav-header") Отчеты
  %li= link_to "Бюджетный календарь", "#"
  %li= link_to "БДДС", "#"
  %li= link_to "БДР", "#"
%ul(class="nav nav-list" id="nav-misc")
  %li(class="nav-header") Служебные
  %li= link_to "Пользователи", users_path
  %li= link_to "Бизнес-процессы", chainlets_path

app/views/layouts/_page_header.haml
%div{:class => "content-header"}
  %div{:class => "row"}
    %div{:class => "span10"}
      %h3
        - if header.back_path.present?
          = link_to header.back_path do
            %i.icon-backward
        = header.headline
      - if header.actions.any?
        %div{:class => "page-actions"}
          - header.actions.each do |act|
            %a{:class => "#{act[:type]}", :href => "#{act[:path]}"}
              =act[:text]
              %i{:class => "icon-#{act[:icon]} icon-large"}

  - if header.crumbs.any?
    %div{:class => "row"}
      %div{:class => "span10"}
        %ul{:class => "breadcrumb"}
          - header.crumbs.each do |crumb|
            %li
              =link_to crumb[:text], {:show => crumb[:value]}
              %span.divider /

app/views/layouts/application-old.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AdiskNew</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Le fav and touch icons -->
    <!--link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"-->
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Adisk 2.0</a>
          <div class="container nav-collapse">
            <ul class="nav">
                <li><%= link_to "Личные сообщения", "/path1"  %></li>
                <li><%= link_to "Задания", "/path2"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
            <div class="span2 sidebar-nav">
                <ul class="nav nav-list" id="nav1">
                    <li><%= link_to "В работе", "#"  %></li>
                    <li><%= link_to "На подпись", "#"  %></li>
                  <li class="nav-header" data-toggle="collapse" data-target="#nav1">Документы</li>
                    <li><%= link_to "Бюджеты", "#"  %></li>
                    <li><%= link_to "Заявки на оплату", "#"  %></li>
                    <li><%= link_to "Поступления", "#"  %></li>
                    <li><%= link_to "Служеные записки", "#"  %></li>
                    <li><%= link_to "Другие документы", "#"  %></li>
                  <li class="nav-header">Справочники</li>
                    <li><%= link_to "Контрагенты", "#"  %></li>
                    <li><%= link_to "Счета", "#"  %></li>
                    <li><%= link_to "Организации", "#"  %></li>
                    <li><%= link_to "Подрзаделения", "#"  %></li>
                    <li><%= link_to "Статить доходов", "#"  %></li>
                    <li><%= link_to "Статить расходов", "#"  %></li>
                  <li class="nav-header">Отчеты</li>
                    <li><%= link_to "Бюджетный календарь", "#"  %></li>
                    <li><%= link_to "БДДС", "#"  %></li>
                    <li><%= link_to "БДР", "#"  %></li>
                </ul>
            </div><!--/span-->
            <div class="span10">
              <%= yield %>
            </div>
        </div><!--/row-->
      </div><!--/content-->


    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/application.haml
!!! 5
%html{:lang => 'en'}
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title Adisk 2.0
    = csrf_meta_tags

    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>

    // Le styles
    = stylesheet_link_tag "application", :media => "all"

    / Le fav and touch icons 
    / %link(href="images/favicon.ico" rel="shortcut icon")
    / %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    / %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    / %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")

  %body
    %div(class="navbar navbar-fixed-top")
      %div(class="navbar-inner")
        %div(class="container")
          / %a(class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse")
          /   %span(class="icon-bar")
          /   %span(class="icon-bar")
          /   %span(class="icon-bar")
          %a(class="brand" href="#") Adisk 2.0
          %div(class="container nav-collapse")
            %ul(class="nav")
              %li= link_to "Личные сообщения", "/path1"
              %li= link_to "Задания", "/path2"

    %div(class="container")
      %div(class="content")
        %div(class="row")
          %div(class="span2 sidebar-nav")
            = render :partial => 'layouts/nav'
          %div.span10#app
            = yield

    / Le javascript
    / ================================================== 
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"